# Generated by Django 4.1.4 on 2022-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'In stock'), (2, 'Preorder'), (3, 'Arrival expected'), (4, 'Not Avaliable'), (5, 'Not manufactured')]),
        ),
    ]
